import type { Metadata } from "next";
import { Roboto } from "next/font/google"; //Roboto import
import "./globals.css";
import Navbar from "../app/components/design-system/template/Navbar/Navbar";
import AuthProvider from "../app/DataProvider/AuthProvider/AuthProvider";
import CvDataProvider from "../app/DataProvider/CvDataProvider/CvDataProvider";
import EducationDataProvider from "../app/DataProvider/EducationDataProvider/EducationDataProvider";
import SkillDataProvider from "../app/DataProvider/SkillDataProvider/SkillDataProvider";
import ToastProvider from '../app/components/design-system/atoms/ToastProvider/ToastProvider'
// Roboto font setup
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   <body className={`${roboto.className} antialiased`}>
    <ToastProvider/>
  <AuthProvider>
    <CvDataProvider>
      <EducationDataProvider>
        <SkillDataProvider>
          <Navbar />
          {children}
          <div className="text-center py-5 text-base sm:text-lg text-gray-500">
       <span> &copy;{new Date().getFullYear()} All Things is reserved</span>
          </div>
        </SkillDataProvider>
      </EducationDataProvider>
    </CvDataProvider>
  </AuthProvider>
</body>
    </html>
  );
}
